### ISSUE TITLE
Better privileges separation

### ISSUE THREAD

**Issue by musikid** [musikid/pjdfstest#117]
In order to limit the number of tests which absolutely require root, we should have better grained privileges separation. We already have an example with the [mount capability](https://github.com/musikid/pjdfstest/blob/51dd38e2abd7bd82b1ac0db941a9dcb8477f91ad/rust/src/tests/rmdir.rs#L117), but it would be better if we can think of a better way to implement this and potentially generify it.
The most required privileges are to create the char/block files and change user.

**Comment by asomers** [comment]
I don't think there are very many other such opportunities.  Linux has file system namespace support, which can be used by a non-root user to do privileged stuff like mknod within one single file system.  Nix uses that to test `mount` in Linux.  But it's very complicated to use.  I would rather not try to use it here.
Another possibility that comes to mind are unprivileged fusefs mounts.  If you don't specify `-o default_permissions` when mounting fuse, then the daemon is responsible for verifying permissions.  If the daemon doesn't, then the user who is running the daemon can use mknod, chown, etc .  But I don't think we ought to special-case pjdfstest just for that.
Linux also has a bunch of other capabilities.  For example, `CAP_MKNOD`.  We could use those instead of requiring root.  But we would still have to require root for the other OSes.
