### ISSUE TITLE
per-thread setuid?

### ISSUE THREAD

**Issue by musikid** [musikid/pjdfstest#2]
`setuid` restricts the possibility of using a parallelized test suite, because it change the user for all threads.

**Comment by asomers** [comment]
I suggest two possible solutions:
* Tests that need to change the uid must be run serialized, for example by locking a global "setuid" mutex.  The test must also restore the default uid before unlocking the mutex.
* Tests that need to change the uid must fork a new process for each test case.  The child must exec too, for otherwise it would only be able to call async-signal-safe functions.  So the binary must have some kind of switch that means "do the unprivileged part of test XXX".

IMHO the first option looks easier.

**Comment by musikid** [comment]
I am also in favor of the first option. It shouldn't be a hard performance hit to run them serialized compared to creating processes, right?

**Comment by asomers** [comment]
No, the performance should still be ok.  After all, the existing pjdfstest does everything serialized.
