### ISSUE TITLE
12.t | truncate returns EFBIG or EINVAL if the length argument was greater than the maximum file size

### ISSUE THREAD

**Issue by musikid** [musikid/pjdfstest#74]
To test if `(f)truncate` returns EFBIG or EINVAL, we need to find the file size limit. It could be queried with `getrlimit(RLIMIT_FSIZE,...)`, however it seems to be a per-process limit, therefore I wonder if it's the right approach.
For instance, the original test suite would just try to truncate with a fixed constant (999999999999999) and if it didn't fail, check the size of the file.

[getrlimit page](https://pubs.opengroup.org/onlinepubs/9699919799/functions/getrlimit.html)
[original test file](https://github.com/musikid/pjdfstest/blob/master/tests/truncate/12.t)

**Comment by musikid** [comment]
Most systems don't even have a finite limit, therefore shouldn't we artificially change the limit with [`setrlimit`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/setrlimit.html)?

**Comment by asomers** [comment]
The original test doesn't really do what the description says.  I think the description should be "truncate must not change the file size if it fails with EFBIG or EINVAL because the length argument was greater than the maximum file size".  Separately, I agree that it would be nice to add a test for RLIMIT_FSIZE, but that should be considered an enhancement.  Here's an example of such a test, specifically for fuse: https://github.com/freebsd/freebsd-src/blob/bb7ddd077c2528b37399304d7a9bf70b25c42b47/tests/sys/fs/fusefs/write.cc#L533 .

**Comment by musikid** [comment]
Alright, I understand now, thank you!
