### ISSUE TITLE
Platform-specific syscall

### ISSUE THREAD

**Issue by musikid** [musikid/pjdfstest#8]
Some tests include platform-specific blocks, mostly for FreeBSD.
They are "guarded" by a check if this syscall is supported on the system.

```bash
if supported lchmod; then
	...
fit
```

This could be easily implemented in Rust by using conditional compilation, e.g `#[cfg(...)]` attribute. 
For example, `#[cfg(target_os = "freebsd")]` can be applied to a block, to specify that it should be compiled only on this OS.
However, it makes it harder because we would have to specify the operating system instead of the syscall.

**Comment by asomers** [comment]
I think this is a reasonable approach.  You should only have to specify the OS-syscall relationship once if you do it in src/tests/mod.rs, right?

**Comment by asomers** [comment]
Actually, there will also need to be a supported syscall check at runtime, because even on a given OS not all file systems support all syscalls.  For example ZFS does not support posix_fallocate.  That type of support should be specified in the user's config file.

**Comment by asomers** [comment]
> Should it take multiple file systems instead of one?

Definitely.   However, even a list of file systems won't be sufficient.  We can't know all of the file systems that might use pjdfstest for their development.  It isn't use UFS and ZFS.  It could include, for example, dozens of different FUSE file systems.  We can't hard-code them all here.  That's why we need a user provided config file to specify things like which tests to skip.  Here's my attempt at creating such a file: https://github.com/pjd/pjdfstest/pull/48/files#diff-ae670374d32d98b7ab61177cc1c2f094041ff5a2f4031f193dd0ddaed8813777 .

**Comment by musikid** [comment]
Oh, I understand. I will add support for the configuration file then.

**Comment by musikid** [comment]
Should also be solved thanks to e99869c.
