### ISSUE TITLE
00.t | chflags changes flags

### ISSUE THREAD

**Issue by musikid** [musikid/pjdfstest#97]
The original test suite assumes that no file flag is set for a created file, which isn't true for ZFS, which sets `UF_ARCHIVE`.
Furthermore, it doesn't seem to have support for `UF_ARCHIVE` and consider that no flag is set because of this. I'm not sure on how to handle this case, maybe consider it as a flag which might be set by default?

**Comment by asomers** [comment]
I see.  pjdfstest.c simply ignores UF_ARCHIVED.  It's hard to test file flags in a file system agnostic way, because their implementation is file system dependent.  But the chflags/00.t test doesn't need to check all file flags.  It only needs to that chflags(2) can set and clear _some_ flags.  I suggest changing the test so that it assumes nothing about which flags might be set by default.  So do a `chflags(path, 0)` before testing what the file's default flags are.

**Comment by musikid** [comment]
I did it this way, thank you!
